In [1]:
%matplotlib inline
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [2]:
df_test = pd.read_csv('test.csv')
df_train = pd.read_csv('train.csv')

In [3]:
df_train

color       400       405       410       415       420       425  \
0   green  0.000161  0.000154  0.000288  0.000453  0.000687  0.000930   
1   green  0.000392  0.000345  0.000379  0.000435  0.000590  0.000755   
2   green  0.000310  0.000308  0.000390  0.000523  0.000759  0.000998   
3   green  0.000189  0.000201  0.000367  0.000564  0.000806  0.001025   
4   green  0.000213  0.000075  0.000064  0.000133  0.000312  0.000547   
5   green  0.000200  0.000263  0.000412  0.000591  0.000792  0.000907   
6   green  0.000266  0.000206  0.000310  0.000475  0.000725  0.000936   
7     red  0.000050  0.000167  0.000293  0.000379  0.000418  0.000410   
8     red  0.000139  0.000192  0.000239  0.000294  0.000334  0.000357   
9     red  0.000237  0.000325  0.000401  0.000451  0.000484  0.000490   
10    red  0.000086  0.000181  0.000292  0.000370  0.000409  0.000410   
11    red  0.000147  0.000173  0.000209  0.000252  0.000291  0.000325   
12    red  0.000156  0.000205  0.000240  0.000236  0.000216  0.000179   
13    red  0.000313  0.000356  0.000396  0.000398  0.000366  0.000331   
14   blue  0.001992  0.002239  0.002591  0.003354  0.004393  0.006486   
15   blue  0.002418  0.002366  0.002384  0.002995  0.004095  0.006494   
16   blue  0.002136  0.002089  0.002116  0.002626  0.003659  0.005882   
17   blue  0.002054  0.002170  0.002372  0.002991  0.003999  0.006159   
18   blue  0.002242  0.002276  0.002463  0.003124  0.004169  0.006272   
19   blue  0.001741  0.001900  0.002175  0.002871  0.003982  0.006259   
20   blue  0.002295  0.002329  0.002507  0.003227  0.004457  0.007012   
21  white  0.000878  0.001001  0.001412  0.002288  0.003551  0.005584   
22  white  0.001004  0.001121  0.001526  0.002419  0.003659  0.005604   
23  white  0.001012  0.001371  0.001958  0.002973  0.004285  0.006284   
24  white  0.001067  0.001280  0.001798  0.002803  0.004160  0.006295   
25  white  0.001011  0.001213  0.001847  0.003018  0.004571  0.006921   
26  white  0.000995  0.001342  0.001973  0.003132  0.004634  0.006809   
27  white  0.000978  0.001234  0.001739  0.002676  0.003974  0.006032   
28    NaN       NaN       NaN       NaN       NaN       NaN       NaN   

         430       435       440  ...       955           960       965  \
0   0.001072  0.001066  0.000961  ...  0.000166  1.828450e-04  0.000199   
1   0.000905  0.000940  0.000914  ...  0.000000  0.000000e+00  0.000014   
2   0.001174  0.001160  0.000975  ...  0.000000  0.000000e+00  0.000000   
3   0.001143  0.001086  0.000914  ...  0.000000  7.940000e-07  0.000040   
4   0.000754  0.000889  0.000991  ...  0.000000  0.000000e+00  0.000000   
5   0.000932  0.000811  0.000653  ...  0.000000  0.000000e+00  0.000000   
6   0.001067  0.000991  0.000913  ...  0.000000  0.000000e+00  0.000000   
7   0.000352  0.000293  0.000256  ...  0.000090  7.562690e-05  0.000073   
8   0.000363  0.000380  0.000410  ...  0.000032  2.911680e-05  0.000041   
9   0.000477  0.000445  0.000367  ...  0.000000  0.000000e+00  0.000000   
10  0.000371  0.000337  0.000316  ...  0.000046  2.393600e-05  0.000010   
11  0.000337  0.000379  0.000423  ...  0.000128  1.348920e-04  0.000145   
12  0.000138  0.000136  0.000172  ...  0.000000  0.000000e+00  0.000020   
13  0.000302  0.000327  0.000399  ...  0.000096  7.900140e-05  0.000083   
14  0.012477  0.019855  0.031027  ...  0.000160  1.663560e-04  0.000208   
15  0.013457  0.022050  0.035056  ...  0.000158  2.274340e-04  0.000337   
16  0.012112  0.019636  0.030780  ...  0.000012  3.153670e-05  0.000046   
17  0.012395  0.020047  0.031507  ...  0.000000  0.000000e+00  0.000000   
18  0.012288  0.019685  0.030964  ...  0.000000  0.000000e+00  0.000000   
19  0.012619  0.020393  0.031963  ...  0.000000  4.426960e-05  0.000133   
20  0.014120  0.022783  0.035824  ...  0.000394  4.270260e-04  0.000513   
21  0.008795  0.012560  0.017427  ...  0.000000  0.000000e+00  0.000000   
22  0.008616  0.012162  0.016815  ...  0.000000  0.000000e+00  0.000000   
23  0.009397 

In [4]:
nba_train = df_train.dropna()

In [5]:
nba_train

color       400       405       410       415       420       425  \
0   green  0.000161  0.000154  0.000288  0.000453  0.000687  0.000930   
1   green  0.000392  0.000345  0.000379  0.000435  0.000590  0.000755   
2   green  0.000310  0.000308  0.000390  0.000523  0.000759  0.000998   
3   green  0.000189  0.000201  0.000367  0.000564  0.000806  0.001025   
4   green  0.000213  0.000075  0.000064  0.000133  0.000312  0.000547   
5   green  0.000200  0.000263  0.000412  0.000591  0.000792  0.000907   
6   green  0.000266  0.000206  0.000310  0.000475  0.000725  0.000936   
7     red  0.000050  0.000167  0.000293  0.000379  0.000418  0.000410   
8     red  0.000139  0.000192  0.000239  0.000294  0.000334  0.000357   
9     red  0.000237  0.000325  0.000401  0.000451  0.000484  0.000490   
10    red  0.000086  0.000181  0.000292  0.000370  0.000409  0.000410   
11    red  0.000147  0.000173  0.000209  0.000252  0.000291  0.000325   
12    red  0.000156  0.000205  0.000240  0.000236  0.000216  0.000179   
13    red  0.000313  0.000356  0.000396  0.000398  0.000366  0.000331   
14   blue  0.001992  0.002239  0.002591  0.003354  0.004393  0.006486   
15   blue  0.002418  0.002366  0.002384  0.002995  0.004095  0.006494   
16   blue  0.002136  0.002089  0.002116  0.002626  0.003659  0.005882   
17   blue  0.002054  0.002170  0.002372  0.002991  0.003999  0.006159   
18   blue  0.002242  0.002276  0.002463  0.003124  0.004169  0.006272   
19   blue  0.001741  0.001900  0.002175  0.002871  0.003982  0.006259   
20   blue  0.002295  0.002329  0.002507  0.003227  0.004457  0.007012   
21  white  0.000878  0.001001  0.001412  0.002288  0.003551  0.005584   
22  white  0.001004  0.001121  0.001526  0.002419  0.003659  0.005604   
23  white  0.001012  0.001371  0.001958  0.002973  0.004285  0.006284   
24  white  0.001067  0.001280  0.001798  0.002803  0.004160  0.006295   
25  white  0.001011  0.001213  0.001847  0.003018  0.004571  0.006921   
26  white  0.000995  0.001342  0.001973  0.003132  0.004634  0.006809   
27  white  0.000978  0.001234  0.001739  0.002676  0.003974  0.006032   

         430       435       440  ...       955           960       965  \
0   0.001072  0.001066  0.000961  ...  0.000166  1.828450e-04  0.000199   
1   0.000905  0.000940  0.000914  ...  0.000000  0.000000e+00  0.000014   
2   0.001174  0.001160  0.000975  ...  0.000000  0.000000e+00  0.000000   
3   0.001143  0.001086  0.000914  ...  0.000000  7.940000e-07  0.000040   
4   0.000754  0.000889  0.000991  ...  0.000000  0.000000e+00  0.000000   
5   0.000932  0.000811  0.000653  ...  0.000000  0.000000e+00  0.000000   
6   0.001067  0.000991  0.000913  ...  0.000000  0.000000e+00  0.000000   
7   0.000352  0.000293  0.000256  ...  0.000090  7.562690e-05  0.000073   
8   0.000363  0.000380  0.000410  ...  0.000032  2.911680e-05  0.000041   
9   0.000477  0.000445  0.000367  ...  0.000000  0.000000e+00  0.000000   
10  0.000371  0.000337  0.000316  ...  0.000046  2.393600e-05  0.000010   
11  0.000337  0.000379  0.000423  ...  0.000128  1.348920e-04  0.000145   
12  0.000138  0.000136  0.000172  ...  0.000000  0.000000e+00  0.000020   
13  0.000302  0.000327  0.000399  ...  0.000096  7.900140e-05  0.000083   
14  0.012477  0.019855  0.031027  ...  0.000160  1.663560e-04  0.000208   
15  0.013457  0.022050  0.035056  ...  0.000158  2.274340e-04  0.000337   
16  0.012112  0.019636  0.030780  ...  0.000012  3.153670e-05  0.000046   
17  0.012395  0.020047  0.031507  ...  0.000000  0.000000e+00  0.000000   
18  0.012288  0.019685  0.030964  ...  0.000000  0.000000e+00  0.000000   
19  0.012619  0.020393  0.031963  ...  0.000000  4.426960e-05  0.000133   
20  0.014120  0.022783  0.035824  ...  0.000394  4.270260e-04  0.000513   
21  0.008795  0.012560  0.017427  ...  0.000000  0.000000e+00  0.000000   
22  0.008616  0.012162  0.016815  ...  0.000000  0.000000e+00  0.000000   
23  0.009397  0.013048  0.017788  ...  0.000000  0.000000e+00  0.000000   
24  0.00967

In [6]:
df_test

color       400       405       410       415       420       425  \
0   green  0.000367  0.000356  0.000412  0.000473  0.000598  0.000734   
1   green  0.000488  0.000583  0.000716  0.000844  0.000964  0.001057   
2   green  0.000393  0.000349  0.000380  0.000430  0.000565  0.000733   
3     red  0.000321  0.000362  0.000393  0.000401  0.000401  0.000408   
4     red  0.000195  0.000253  0.000285  0.000313  0.000316  0.000306   
5     red  0.000273  0.000323  0.000370  0.000406  0.000408  0.000373   
6    blue  0.002344  0.002372  0.002450  0.003055  0.004108  0.006480   
7    blue  0.002157  0.002380  0.002627  0.003164  0.003949  0.005762   
8    blue  0.002223  0.002334  0.002510  0.003132  0.004290  0.006873   
9   white  0.000909  0.001011  0.001414  0.002339  0.003706  0.005860   
10  white  0.001005  0.001241  0.001749  0.002756  0.004072  0.006086   
11  white  0.001047  0.001199  0.001617  0.002536  0.003826  0.005861   

         430       435       440  ...       955       960       965  \
0   0.000855  0.000893  0.000871  ...  0.000000  0.000000  0.000000   
1   0.001159  0.001160  0.001047  ...  0.000000  0.000000  0.000000   
2   0.000878  0.000903  0.000795  ...  0.000000  0.000000  0.000000   
3   0.000379  0.000342  0.000266  ...  0.000047  0.000038  0.000042   
4   0.000278  0.000281  0.000292  ...  0.000084  0.000072  0.000076   
5   0.000329  0.000299  0.000297  ...  0.000117  0.000114  0.000129   
6   0.013305  0.021684  0.034109  ...  0.000000  0.000000  0.000000   
7   0.011434  0.018480  0.029157  ...  0.000000  0.000000  0.000014   
8   0.014038  0.022902  0.036050  ...  0.000033  0.000060  0.000101   
9   0.009101  0.012844  0.017620  ...  0.000000  0.000000  0.000000   
10  0.009160  0.012817  0.017596  ...  0.000172  0.000155  0.000110   
11  0.009139  0.012924  0.017864  ...  0.000000  0.000000  0.000000   

             970       975       980       985       990       995      1000  
0   3.780000e-05  0.000103  0.000162  0.000215  0.000238  0.000295  0.000345  
1   0.000000e+00  0.000043  0.000091  0.000127  0.000141  0.000194  0.000241  
2   0.000000e+00  0.000023  0.000046  0.000018  0.000024  0.000046  0.000066  
3   2.590000e-05  0.000019  0.000016  0.000058  0.000031  0.000027  0.000028  
4   5.430000e-05  0.000035  0.000010  0.000021  0.000000  0.000000  0.000000  
5   1.231320e-04  0.000124  0.000115  0.000143  0.000113  0.000111  0.000118  
6   6.920000e-05  0.000194  0.000333  0.000513  0.000644  0.000817  0.000968  
7   2.180000e-05  0.000074  0.000143  0.000314  0.000398  0.000491  0.000581  
8   1.622070e-04  0.000237  0.000349  0.000459  0.000525  0.000640  0.000747  
9   0.000000e+00  0.000000  0.000005  0.000153  0.000157  0.000211  0.000267  
10  6.580000e-05  0.000036  0.000000  0.000000  0.000000  0.000000  0.000000  
11  4.190000e-07  0.000036  0.000078  0.000210  0.000193  0.000225  0.000251  

[12 rows x 122 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
def color_to_int(data):
    le = LabelEncoder()
    le.fit(["green","red","blue","white"])
    data["color"]=le.transform(data["color"]) 
    return data

train_data = color_to_int(nba_train)
test_data = color_to_int(df_test)

C:\Users\xiangjun\AppData\Local\conda\conda\envs\py36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [8]:
train_data

color       400       405       410       415       420       425  \
0       1  0.000161  0.000154  0.000288  0.000453  0.000687  0.000930   
1       1  0.000392  0.000345  0.000379  0.000435  0.000590  0.000755   
2       1  0.000310  0.000308  0.000390  0.000523  0.000759  0.000998   
3       1  0.000189  0.000201  0.000367  0.000564  0.000806  0.001025   
4       1  0.000213  0.000075  0.000064  0.000133  0.000312  0.000547   
5       1  0.000200  0.000263  0.000412  0.000591  0.000792  0.000907   
6       1  0.000266  0.000206  0.000310  0.000475  0.000725  0.000936   
7       2  0.000050  0.000167  0.000293  0.000379  0.000418  0.000410   
8       2  0.000139  0.000192  0.000239  0.000294  0.000334  0.000357   
9       2  0.000237  0.000325  0.000401  0.000451  0.000484  0.000490   
10      2  0.000086  0.000181  0.000292  0.000370  0.000409  0.000410   
11      2  0.000147  0.000173  0.000209  0.000252  0.000291  0.000325   
12      2  0.000156  0.000205  0.000240  0.000236  0.000216  0.000179   
13      2  0.000313  0.000356  0.000396  0.000398  0.000366  0.000331   
14      0  0.001992  0.002239  0.002591  0.003354  0.004393  0.006486   
15      0  0.002418  0.002366  0.002384  0.002995  0.004095  0.006494   
16      0  0.002136  0.002089  0.002116  0.002626  0.003659  0.005882   
17      0  0.002054  0.002170  0.002372  0.002991  0.003999  0.006159   
18      0  0.002242  0.002276  0.002463  0.003124  0.004169  0.006272   
19      0  0.001741  0.001900  0.002175  0.002871  0.003982  0.006259   
20      0  0.002295  0.002329  0.002507  0.003227  0.004457  0.007012   
21      3  0.000878  0.001001  0.001412  0.002288  0.003551  0.005584   
22      3  0.001004  0.001121  0.001526  0.002419  0.003659  0.005604   
23      3  0.001012  0.001371  0.001958  0.002973  0.004285  0.006284   
24      3  0.001067  0.001280  0.001798  0.002803  0.004160  0.006295   
25      3  0.001011  0.001213  0.001847  0.003018  0.004571  0.006921   
26      3  0.000995  0.001342  0.001973  0.003132  0.004634  0.006809   
27      3  0.000978  0.001234  0.001739  0.002676  0.003974  0.006032   

         430       435       440  ...       955           960       965  \
0   0.001072  0.001066  0.000961  ...  0.000166  1.828450e-04  0.000199   
1   0.000905  0.000940  0.000914  ...  0.000000  0.000000e+00  0.000014   
2   0.001174  0.001160  0.000975  ...  0.000000  0.000000e+00  0.000000   
3   0.001143  0.001086  0.000914  ...  0.000000  7.940000e-07  0.000040   
4   0.000754  0.000889  0.000991  ...  0.000000  0.000000e+00  0.000000   
5   0.000932  0.000811  0.000653  ...  0.000000  0.000000e+00  0.000000   
6   0.001067  0.000991  0.000913  ...  0.000000  0.000000e+00  0.000000   
7   0.000352  0.000293  0.000256  ...  0.000090  7.562690e-05  0.000073   
8   0.000363  0.000380  0.000410  ...  0.000032  2.911680e-05  0.000041   
9   0.000477  0.000445  0.000367  ...  0.000000  0.000000e+00  0.000000   
10  0.000371  0.000337  0.000316  ...  0.000046  2.393600e-05  0.000010   
11  0.000337  0.000379  0.000423  ...  0.000128  1.348920e-04  0.000145   
12  0.000138  0.000136  0.000172  ...  0.000000  0.000000e+00  0.000020   
13  0.000302  0.000327  0.000399  ...  0.000096  7.900140e-05  0.000083   
14  0.012477  0.019855  0.031027  ...  0.000160  1.663560e-04  0.000208   
15  0.013457  0.022050  0.035056  ...  0.000158  2.274340e-04  0.000337   
16  0.012112  0.019636  0.030780  ...  0.000012  3.153670e-05  0.000046   
17  0.012395  0.020047  0.031507  ...  0.000000  0.000000e+00  0.000000   
18  0.012288  0.019685  0.030964  ...  0.000000  0.000000e+00  0.000000   
19  0.012619  0.020393  0.031963  ...  0.000000  4.426960e-05  0.000133   
20  0.014120  0.022783  0.035824  ...  0.000394  4.270260e-04  0.000513   
21  0.008795  0.012560  0.017427  ...  0.000000  0.000000e+00  0.000000   
22  0.008616  0.012162  0.016815  ...  0.000000  0.000000e+00  0.000000   
23  0.009397  0.013048  0.017788  ...  0.000000  0.000000e+00  0.000000   
24  0.00967

In [9]:
#one-hot encoding
#color_0=blue,color_1=green,color_2=red,color_3=white
train_onehot = pd.get_dummies(data=nba_train,columns=['color'])
test_onehot = pd.get_dummies(data=df_test,columns=['color'])
pd.DataFrame(train_onehot)

400       405       410       415       420       425       430  \
0   0.000161  0.000154  0.000288  0.000453  0.000687  0.000930  0.001072   
1   0.000392  0.000345  0.000379  0.000435  0.000590  0.000755  0.000905   
2   0.000310  0.000308  0.000390  0.000523  0.000759  0.000998  0.001174   
3   0.000189  0.000201  0.000367  0.000564  0.000806  0.001025  0.001143   
4   0.000213  0.000075  0.000064  0.000133  0.000312  0.000547  0.000754   
5   0.000200  0.000263  0.000412  0.000591  0.000792  0.000907  0.000932   
6   0.000266  0.000206  0.000310  0.000475  0.000725  0.000936  0.001067   
7   0.000050  0.000167  0.000293  0.000379  0.000418  0.000410  0.000352   
8   0.000139  0.000192  0.000239  0.000294  0.000334  0.000357  0.000363   
9   0.000237  0.000325  0.000401  0.000451  0.000484  0.000490  0.000477   
10  0.000086  0.000181  0.000292  0.000370  0.000409  0.000410  0.000371   
11  0.000147  0.000173  0.000209  0.000252  0.000291  0.000325  0.000337   
12  0.000156  0.000205  0.000240  0.000236  0.000216  0.000179  0.000138   
13  0.000313  0.000356  0.000396  0.000398  0.000366  0.000331  0.000302   
14  0.001992  0.002239  0.002591  0.003354  0.004393  0.006486  0.012477   
15  0.002418  0.002366  0.002384  0.002995  0.004095  0.006494  0.013457   
16  0.002136  0.002089  0.002116  0.002626  0.003659  0.005882  0.012112   
17  0.002054  0.002170  0.002372  0.002991  0.003999  0.006159  0.012395   
18  0.002242  0.002276  0.002463  0.003124  0.004169  0.006272  0.012288   
19  0.001741  0.001900  0.002175  0.002871  0.003982  0.006259  0.012619   
20  0.002295  0.002329  0.002507  0.003227  0.004457  0.007012  0.014120   
21  0.000878  0.001001  0.001412  0.002288  0.003551  0.005584  0.008795   
22  0.001004  0.001121  0.001526  0.002419  0.003659  0.005604  0.008616   
23  0.001012  0.001371  0.001958  0.002973  0.004285  0.006284  0.009397   
24  0.001067  0.001280  0.001798  0.002803  0.004160  0.006295  0.009674   
25  0.001011  0.001213  0.001847  0.003018  0.004571  0.006921  0.010489   
26  0.000995  0.001342  0.001973  0.003132  0.004634  0.006809  0.010080   
27  0.000978  0.001234  0.001739  0.002676  0.003974  0.006032  0.009196   

         435       440       445  ...           975           980       985  \
0   0.001066  0.000961  0.000862  ...  2.144630e-04  2.288380e-04  0.000204   
1   0.000940  0.000914  0.000769  ...  1.043620e-04  1.563910e-04  0.000183   
2   0.001160  0.000975  0.000759  ...  2.820000e-07  6.190460e-05  0.000045   
3   0.001086  0.000914  0.000736  ...  1.361140e-04  1.905850e-04  0.000214   
4   0.000889  0.000991  0.001086  ...  4.262070e-05  9.629790e-05  0.000091   
5   0.000811  0.000653  0.000415  ...  0.000000e+00  0.000000e+00  0.000000   
6   0.000991  0.000913  0.000789  ...  5.208360e-05  1.096790e-04  0.000152   
7   0.000293  0.000256  0.000188  ...  3.040310e-05  1.226240e-05  0.000002   
8   0.000380  0.000410  0.000381  ...  3.006290e-05  3.104690e-05  0.000108   
9   0.000445  0.000367  0.000272  ...  0.000000e+00  0.000000e+00  0.000002   
10  0.000337  0.000316  0.000323  ...  0.000000e+00  0.000000e+00  0.000000   
11  0.000379  0.000423  0.000446  ...  1.460700e-04  1.558920e-04  0.000204   
12  0.000136  0.000172  0.000198  ...  4.971050e-05  6.132600e-05  0.000131   
13  0.000327  0.000399  0.000380  ...  5.980850e-05  4.405710e-05  0.000057   
14  0.019855  0.031027  0.046335  ...  2.843510e-04  3.127480e-04  0.000435   
15  0.022050  0.035056  0.052767  ...  5.617380e-04  6.514400e-04  0.000847   
16  0.019636  0.030780  0.045847  ...  1.470620e-04  2.149290e-04  0.000321   
17  0.020047  0.031507  0.047172  ...  0.000000e+00  0.000000e+00  0.000069   
18  0.019685  0.030964  0.046455  ...  0.000000e+00  8.269040e-05  0.000232   
19  0.020393  0.031963  0.047708  ...  3.144610e-04  4.031280e-04  0.000554   
20  0.022783  0.035824  0.053315  ...  6.473030e-04  7.097710e-04  0.000813   
21  0.012560  0.017427  0.022339  ...  0.000000e+00  0.000000e+00 

In [10]:
pd.DataFrame(test_onehot)

400       405       410       415       420       425       430  \
0   0.000367  0.000356  0.000412  0.000473  0.000598  0.000734  0.000855   
1   0.000488  0.000583  0.000716  0.000844  0.000964  0.001057  0.001159   
2   0.000393  0.000349  0.000380  0.000430  0.000565  0.000733  0.000878   
3   0.000321  0.000362  0.000393  0.000401  0.000401  0.000408  0.000379   
4   0.000195  0.000253  0.000285  0.000313  0.000316  0.000306  0.000278   
5   0.000273  0.000323  0.000370  0.000406  0.000408  0.000373  0.000329   
6   0.002344  0.002372  0.002450  0.003055  0.004108  0.006480  0.013305   
7   0.002157  0.002380  0.002627  0.003164  0.003949  0.005762  0.011434   
8   0.002223  0.002334  0.002510  0.003132  0.004290  0.006873  0.014038   
9   0.000909  0.001011  0.001414  0.002339  0.003706  0.005860  0.009101   
10  0.001005  0.001241  0.001749  0.002756  0.004072  0.006086  0.009160   
11  0.001047  0.001199  0.001617  0.002536  0.003826  0.005861  0.009139   

         435       440       445  ...       975       980       985       990  \
0   0.000893  0.000871  0.000786  ...  0.000103  0.000162  0.000215  0.000238   
1   0.001160  0.001047  0.000888  ...  0.000043  0.000091  0.000127  0.000141   
2   0.000903  0.000795  0.000730  ...  0.000023  0.000046  0.000018  0.000024   
3   0.000342  0.000266  0.000185  ...  0.000019  0.000016  0.000058  0.000031   
4   0.000281  0.000292  0.000286  ...  0.000035  0.000010  0.000021  0.000000   
5   0.000299  0.000297  0.000265  ...  0.000124  0.000115  0.000143  0.000113   
6   0.021684  0.034109  0.051087  ...  0.000194  0.000333  0.000513  0.000644   
7   0.018480  0.029157  0.043697  ...  0.000074  0.000143  0.000314  0.000398   
8   0.022902  0.036050  0.053782  ...  0.000237  0.000349  0.000459  0.000525   
9   0.012844  0.017620  0.022455  ...  0.000000  0.000005  0.000153  0.000157   
10  0.012817  0.017596  0.022537  ...  0.000036  0.000000  0.000000  0.000000   
11  0.012924  0.017864  0.022996  ...  0.000036  0.000078  0.000210  0.000193   

         995      1000  color_0  color_1  color_2  color_3  
0   0.000295  0.000345        0        1        0        0  
1   0.000194  0.000241        0        1        0        0  
2   0.000046  0.000066        0        1        0        0  
3   0.000027  0.000028        0        0        1        0  
4   0.000000  0.000000        0        0        1        0  
5   0.000111  0.000118        0        0        1        0  
6   0.000817  0.000968        1        0        0        0  
7   0.000491  0.000581        1        0        0        0  
8   0.000640  0.000747        1        0        0        0  
9   0.000211  0.000267        0        0        0        1  
10  0.000000  0.000000        0        0        0        1  
11  0.000225  0.000251        0        0        0        1  

[12 rows x 125 columns]

In [11]:
train_label = pd.get_dummies(nba_train['color'])
test_label = pd.get_dummies(df_test['color'])
pd.DataFrame(train_label)

0  1  2  3
0   0  1  0  0
1   0  1  0  0
2   0  1  0  0
3   0  1  0  0
4   0  1  0  0
5   0  1  0  0
6   0  1  0  0
7   0  0  1  0
8   0  0  1  0
9   0  0  1  0
10  0  0  1  0
11  0  0  1  0
12  0  0  1  0
13  0  0  1  0
14  1  0  0  0
15  1  0  0  0
16  1  0  0  0
17  1  0  0  0
18  1  0  0  0
19  1  0  0  0
20  1  0  0  0
21  0  0  0  1
22  0  0  0  1
23  0  0  0  1
24  0  0  0  1
25  0  0  0  1
26  0  0  0  1
27  0  0  0  1

In [12]:
pd.DataFrame(test_label)

0  1  2  3
0   0  1  0  0
1   0  1  0  0
2   0  1  0  0
3   0  0  1  0
4   0  0  1  0
5   0  0  1  0
6   1  0  0  0
7   1  0  0  0
8   1  0  0  0
9   0  0  0  1
10  0  0  0  1
11  0  0  0  1

In [13]:
train_image=train_data.drop(['color'], axis=1)
test_image=test_data.drop(['color'], axis=1)
train_image

400       405       410       415       420       425       430  \
0   0.000161  0.000154  0.000288  0.000453  0.000687  0.000930  0.001072   
1   0.000392  0.000345  0.000379  0.000435  0.000590  0.000755  0.000905   
2   0.000310  0.000308  0.000390  0.000523  0.000759  0.000998  0.001174   
3   0.000189  0.000201  0.000367  0.000564  0.000806  0.001025  0.001143   
4   0.000213  0.000075  0.000064  0.000133  0.000312  0.000547  0.000754   
5   0.000200  0.000263  0.000412  0.000591  0.000792  0.000907  0.000932   
6   0.000266  0.000206  0.000310  0.000475  0.000725  0.000936  0.001067   
7   0.000050  0.000167  0.000293  0.000379  0.000418  0.000410  0.000352   
8   0.000139  0.000192  0.000239  0.000294  0.000334  0.000357  0.000363   
9   0.000237  0.000325  0.000401  0.000451  0.000484  0.000490  0.000477   
10  0.000086  0.000181  0.000292  0.000370  0.000409  0.000410  0.000371   
11  0.000147  0.000173  0.000209  0.000252  0.000291  0.000325  0.000337   
12  0.000156  0.000205  0.000240  0.000236  0.000216  0.000179  0.000138   
13  0.000313  0.000356  0.000396  0.000398  0.000366  0.000331  0.000302   
14  0.001992  0.002239  0.002591  0.003354  0.004393  0.006486  0.012477   
15  0.002418  0.002366  0.002384  0.002995  0.004095  0.006494  0.013457   
16  0.002136  0.002089  0.002116  0.002626  0.003659  0.005882  0.012112   
17  0.002054  0.002170  0.002372  0.002991  0.003999  0.006159  0.012395   
18  0.002242  0.002276  0.002463  0.003124  0.004169  0.006272  0.012288   
19  0.001741  0.001900  0.002175  0.002871  0.003982  0.006259  0.012619   
20  0.002295  0.002329  0.002507  0.003227  0.004457  0.007012  0.014120   
21  0.000878  0.001001  0.001412  0.002288  0.003551  0.005584  0.008795   
22  0.001004  0.001121  0.001526  0.002419  0.003659  0.005604  0.008616   
23  0.001012  0.001371  0.001958  0.002973  0.004285  0.006284  0.009397   
24  0.001067  0.001280  0.001798  0.002803  0.004160  0.006295  0.009674   
25  0.001011  0.001213  0.001847  0.003018  0.004571  0.006921  0.010489   
26  0.000995  0.001342  0.001973  0.003132  0.004634  0.006809  0.010080   
27  0.000978  0.001234  0.001739  0.002676  0.003974  0.006032  0.009196   

         435       440       445  ...       955           960       965  \
0   0.001066  0.000961  0.000862  ...  0.000166  1.828450e-04  0.000199   
1   0.000940  0.000914  0.000769  ...  0.000000  0.000000e+00  0.000014   
2   0.001160  0.000975  0.000759  ...  0.000000  0.000000e+00  0.000000   
3   0.001086  0.000914  0.000736  ...  0.000000  7.940000e-07  0.000040   
4   0.000889  0.000991  0.001086  ...  0.000000  0.000000e+00  0.000000   
5   0.000811  0.000653  0.000415  ...  0.000000  0.000000e+00  0.000000   
6   0.000991  0.000913  0.000789  ...  0.000000  0.000000e+00  0.000000   
7   0.000293  0.000256  0.000188  ...  0.000090  7.562690e-05  0.000073   
8   0.000380  0.000410  0.000381  ...  0.000032  2.911680e-05  0.000041   
9   0.000445  0.000367  0.000272  ...  0.000000  0.000000e+00  0.000000   
10  0.000337  0.000316  0.000323  ...  0.000046  2.393600e-05  0.000010   
11  0.000379  0.000423  0.000446  ...  0.000128  1.348920e-04  0.000145   
12  0.000136  0.000172  0.000198  ...  0.000000  0.000000e+00  0.000020   
13  0.000327  0.000399  0.000380  ...  0.000096  7.900140e-05  0.000083   
14  0.019855  0.031027  0.046335  ...  0.000160  1.663560e-04  0.000208   
15  0.022050  0.035056  0.052767  ...  0.000158  2.274340e-04  0.000337   
16  0.019636  0.030780  0.045847  ...  0.000012  3.153670e-05  0.000046   
17  0.020047  0.031507  0.047172  ...  0.000000  0.000000e+00  0.000000   
18  0.019685  0.030964  0.046455  ...  0.000000  0.000000e+00  0.000000   
19  0.020393  0.031963  0.047708  ...  0.000000  4.426960e-05  0.000133   
20  0.022783  0.035824  0.053315  ...  0.000394  4.270260e-04  0.000513   
21  0.012560  0.017427  0.022339  ...  0.000000  0.000000e+00  0.000000   
22  0.012162  0.016815  0.021495  ...  0.000000  0.000000e+00  0.000000   
23  

In [14]:
test_image

400       405       410       415       420       425       430  \
0   0.000367  0.000356  0.000412  0.000473  0.000598  0.000734  0.000855   
1   0.000488  0.000583  0.000716  0.000844  0.000964  0.001057  0.001159   
2   0.000393  0.000349  0.000380  0.000430  0.000565  0.000733  0.000878   
3   0.000321  0.000362  0.000393  0.000401  0.000401  0.000408  0.000379   
4   0.000195  0.000253  0.000285  0.000313  0.000316  0.000306  0.000278   
5   0.000273  0.000323  0.000370  0.000406  0.000408  0.000373  0.000329   
6   0.002344  0.002372  0.002450  0.003055  0.004108  0.006480  0.013305   
7   0.002157  0.002380  0.002627  0.003164  0.003949  0.005762  0.011434   
8   0.002223  0.002334  0.002510  0.003132  0.004290  0.006873  0.014038   
9   0.000909  0.001011  0.001414  0.002339  0.003706  0.005860  0.009101   
10  0.001005  0.001241  0.001749  0.002756  0.004072  0.006086  0.009160   
11  0.001047  0.001199  0.001617  0.002536  0.003826  0.005861  0.009139   

         435       440       445  ...       955       960       965  \
0   0.000893  0.000871  0.000786  ...  0.000000  0.000000  0.000000   
1   0.001160  0.001047  0.000888  ...  0.000000  0.000000  0.000000   
2   0.000903  0.000795  0.000730  ...  0.000000  0.000000  0.000000   
3   0.000342  0.000266  0.000185  ...  0.000047  0.000038  0.000042   
4   0.000281  0.000292  0.000286  ...  0.000084  0.000072  0.000076   
5   0.000299  0.000297  0.000265  ...  0.000117  0.000114  0.000129   
6   0.021684  0.034109  0.051087  ...  0.000000  0.000000  0.000000   
7   0.018480  0.029157  0.043697  ...  0.000000  0.000000  0.000014   
8   0.022902  0.036050  0.053782  ...  0.000033  0.000060  0.000101   
9   0.012844  0.017620  0.022455  ...  0.000000  0.000000  0.000000   
10  0.012817  0.017596  0.022537  ...  0.000172  0.000155  0.000110   
11  0.012924  0.017864  0.022996  ...  0.000000  0.000000  0.000000   

             970       975       980       985       990       995      1000  
0   3.780000e-05  0.000103  0.000162  0.000215  0.000238  0.000295  0.000345  
1   0.000000e+00  0.000043  0.000091  0.000127  0.000141  0.000194  0.000241  
2   0.000000e+00  0.000023  0.000046  0.000018  0.000024  0.000046  0.000066  
3   2.590000e-05  0.000019  0.000016  0.000058  0.000031  0.000027  0.000028  
4   5.430000e-05  0.000035  0.000010  0.000021  0.000000  0.000000  0.000000  
5   1.231320e-04  0.000124  0.000115  0.000143  0.000113  0.000111  0.000118  
6   6.920000e-05  0.000194  0.000333  0.000513  0.000644  0.000817  0.000968  
7   2.180000e-05  0.000074  0.000143  0.000314  0.000398  0.000491  0.000581  
8   1.622070e-04  0.000237  0.000349  0.000459  0.000525  0.000640  0.000747  
9   0.000000e+00  0.000000  0.000005  0.000153  0.000157  0.000211  0.000267  
10  6.580000e-05  0.000036  0.000000  0.000000  0.000000  0.000000  0.000000  
11  4.190000e-07  0.000036  0.000078  0.000210  0.000193  0.000225  0.000251  

[12 rows x 121 columns]

In [15]:
#資料預處理完成
print('train image:',train_image.shape)
print('train label:',train_label.shape)
print('test image:',test_image.shape)
print('test label:',test_label.shape)

train image: (28, 121)
train label: (28, 4)
test image: (12, 121)
test label: (12, 4)


In [16]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [17]:
#建構神經網路
n_input=121
n_hidden_1=64
n_hidden_2=64
n_classes=4
x=tf.placeholder(tf.float32,[None,n_input])
y_=tf.placeholder(tf.float32,[None,n_classes])

with tf.name_scope('hidden1'):
    weights=tf.Variable(tf.random_normal([n_input,n_hidden_1]),name='weights')
    biases=tf.Variable(tf.random_normal([n_hidden_1]),name='biases')
    layer_1=tf.matmul(x,weights)+biases
    
with tf.name_scope('hidden2'):
    weights=tf.Variable(tf.random_normal([n_hidden_1,n_hidden_2]),name='weights')
    biases=tf.Variable(tf.random_normal([n_hidden_2]),name='biases')
    layer_2=tf.matmul(layer_1,weights)+biases

with tf.name_scope('output'):
    weights=tf.Variable(tf.random_normal([n_hidden_1,n_classes]),name='weights')
    biases=tf.Variable(tf.random_normal([n_classes]),name='biases')
    logits=tf.matmul(layer_2,weights)+biases
    predicted = tf.nn.softmax(logits)

In [18]:
learning_rate=0.001
total_step=300

#損失函數
with tf.name_scope('cross_entropy'):
    cross_entropy=tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,labels=y_))
    
with tf.name_scope('train'):
    train_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cross_entropy)

In [19]:
#Accuracy
with tf.name_scope('accuracy'):
    y=tf.nn.softmax(logits)
    correct_prediction=tf.equal(tf.argmax(y,1),tf.argmax(y_,1))
    accuracy=tf.reduce_mean(tf.cast(correct_prediction,'float'))

In [38]:
#Train and Test
init=tf.global_variables_initializer()
batch_size=10

with tf.Session() as sess:
    sess.run(init)
    
    
    for i in range(total_step):
        sess.run(train_step,
               feed_dict={x:train_image,y_:train_label})
        
       
        
        if i % 10 == 0:
            loss,acc=sess.run([cross_entropy,accuracy],
                          feed_dict={x:train_image,y_:train_label})
            test_loss,test_acc=sess.run([cross_entropy,accuracy],
                                   feed_dict={x:test_image,y_:test_label})
            print('step:{:4d}\t loss: {:.3f}\t acc:{:.3f}\t test_loss:{:.3f}\t test_acc: {:.3f}'.
                 format(i,loss,acc,test_loss,test_acc))
    print('-------------------------------------------------------------------------\n')
    test_predict=sess.run(predicted,feed_dict={x : test_image})   
    print(test_predict)

step:   0	 loss: 97.194	 acc:0.250	 test_loss:97.390	 test_acc: 0.250
step:  10	 loss: 31.879	 acc:0.250	 test_loss:32.041	 test_acc: 0.250
step:  20	 loss: 17.567	 acc:0.250	 test_loss:17.817	 test_acc: 0.250
step:  30	 loss: 7.301	 acc:0.464	 test_loss:7.506	 test_acc: 0.500
step:  40	 loss: 6.530	 acc:0.500	 test_loss:6.717	 test_acc: 0.500
step:  50	 loss: 5.792	 acc:0.500	 test_loss:5.950	 test_acc: 0.500
step:  60	 loss: 5.082	 acc:0.500	 test_loss:5.215	 test_acc: 0.500
step:  70	 loss: 4.382	 acc:0.500	 test_loss:4.491	 test_acc: 0.500
step:  80	 loss: 3.689	 acc:0.500	 test_loss:3.776	 test_acc: 0.500
step:  90	 loss: 3.004	 acc:0.500	 test_loss:3.067	 test_acc: 0.500
step: 100	 loss: 2.324	 acc:0.500	 test_loss:2.366	 test_acc: 0.500
step: 110	 loss: 1.665	 acc:0.500	 test_loss:1.685	 test_acc: 0.500
step: 120	 loss: 1.075	 acc:0.500	 test_loss:1.076	 test_acc: 0.500
step: 130	 loss: 0.632	 acc:0.500	 test_loss:0.622	 test_acc: 0.500
step: 140	 loss: 0.374	 acc:0.786	 test_lo

In [40]:
from sklearn.preprocessing import Binarizer
binarizer=Binarizer(0.5)
test_predict_result=binarizer.fit_transform(test_predict)
test_predict_result=test_predict_result.astype(np.int32)
test_predict_result

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

In [42]:
#color_0=blue,color_1=green,color_2=red,color_3=white
test_label

0  1  2  3
0   0  1  0  0
1   0  1  0  0
2   0  1  0  0
3   0  0  1  0
4   0  0  1  0
5   0  0  1  0
6   1  0  0  0
7   1  0  0  0
8   1  0  0  0
9   0  0  0  1
10  0  0  0  1
11  0  0  0  1

In [44]:
#以下為在練習儲存模型&匯入模型

w = tf.Variable(tf.random_normal(shape=[121,4]), name='w')
b = tf.Variable(tf.random_normal(shape=[4]), name='b')
sess = tf.Session()
sess.run(tf.global_variables_initializer())
saver.save(sess, './checkpoint_dir/MyModel')

'./checkpoint_dir/MyModel'

In [45]:
saver=tf.train.import_meta_graph('./checkpoint_dir/MyModel.meta')

In [46]:
with tf.Session() as sess:
    new_saver = tf.train.import_meta_graph('./checkpoint_dir/MyModel.meta')
    new_saver.restore(sess, tf.train.latest_checkpoint('./checkpoint_dir'))

INFO:tensorflow:Restoring parameters from ./checkpoint_dir\MyModel


In [47]:
with tf.Session() as sess:
    saver = tf.train.import_meta_graph('./checkpoint_dir/MyModel.meta')
    saver.restore(sess,tf.train.latest_checkpoint('./checkpoint_dir'))
    print(sess.run('w:0'))

INFO:tensorflow:Restoring parameters from ./checkpoint_dir\MyModel
[[ 1.52974391e+00 -4.82320756e-01  3.41182917e-01 -2.52146626e+00]
 [ 1.38936174e+00  4.25305665e-01 -2.62896031e-01 -1.79142392e+00]
 [ 2.27557302e-01 -2.29357276e-02 -1.19210698e-01  1.31167793e+00]
 [-6.91851795e-01  1.98533082e+00 -2.93119043e-01  1.28588927e+00]
 [ 5.66563249e-01 -9.11268234e-01  2.30799660e-01  1.98504293e+00]
 [-1.32178628e+00 -9.25121546e-01 -1.20146167e+00  4.21550930e-01]
 [ 1.17060661e+00  3.99537198e-02 -8.82990181e-01  1.03547800e+00]
 [-1.45101145e-01 -2.67207742e-01  4.67102498e-01 -1.87857985e+00]
 [ 1.99412741e-02  8.53102863e-01 -9.96690765e-02 -1.07132030e+00]
 [ 1.12195149e-01  3.04334581e-01  1.04049492e+00 -2.39877343e+00]
 [ 7.10955501e-01 -6.91887498e-01  2.06822228e+00  5.45006394e-01]
 [ 6.17147505e-01 -7.38272369e-01 -5.03193140e-01 -1.92584300e+00]
 [-1.49893081e+00  5.97545564e-01  1.23417521e+00  7.81552255e-01]
 [-3.70794564e-01  1.13869381e+00  5.85605025e-01  1.10410400e

In [48]:
with tf.Session() as sess:
    sess.run(init)
    test_predict=sess.run(predicted,feed_dict={x : test_image.values.reshape(12, 121)})

In [49]:
test_predict

array([[1.6434882e-33, 0.0000000e+00, 1.0000000e+00, 4.5873402e-30],
       [2.5540329e-34, 0.0000000e+00, 1.0000000e+00, 1.3252396e-30],
       [7.5603771e-33, 0.0000000e+00, 1.0000000e+00, 1.0612068e-29],
       [1.4476529e-19, 0.0000000e+00, 1.0000000e+00, 3.0077905e-19],
       [8.4330753e-20, 0.0000000e+00, 1.0000000e+00, 1.3203726e-19],
       [1.4213434e-19, 0.0000000e+00, 1.0000000e+00, 3.3769798e-19],
       [1.0820877e-29, 3.8404062e-36, 1.0000000e+00, 1.4611659e-22],
       [9.0278490e-29, 3.2082134e-38, 1.0000000e+00, 9.2200983e-23],
       [4.4999857e-30, 2.5283334e-35, 1.0000000e+00, 1.4099952e-22],
       [8.8242360e-22, 0.0000000e+00, 1.0000000e+00, 2.0809961e-20],
       [1.1309385e-21, 0.0000000e+00, 1.0000000e+00, 1.7550571e-20],
       [1.1514463e-21, 0.0000000e+00, 1.0000000e+00, 1.5911543e-20]],
      dtype=float32)

In [29]:
test_label

0  1  2  3
0   0  1  0  0
1   0  1  0  0
2   0  1  0  0
3   0  0  1  0
4   0  0  1  0
5   0  0  1  0
6   1  0  0  0
7   1  0  0  0
8   1  0  0  0
9   0  0  0  1
10  0  0  0  1
11  0  0  0  1